# Generated by Django 6.1 on 2026-08-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='hotels/'),
        ),
    ]
