# Generated by Django 6.1 on 2026-09-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='currency',
            field=models.CharField(blank=True, default='F XOF', max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
